name: video_compressor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  file_selector: ^0.9.2+2
  get_cli: ^1.8.1
  video_compress: 3.1.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  video_player: ^2.4.8
  syncfusion_flutter_sliders: ^20.3.58
  light_compressor: ^1.2.2
  get_storage: ^2.0.3
  ffmpeg_kit_flutter: ^5.1.0
  share_plus: ^5.0.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

